# services:
#   nest-app:
#     build:
#       context: ./
#       dockerfile: ./Dockerfile
#     depends_on:
#       - mysql-container
#       - redis-container
#     ports:
#       - '3000:3000'
#   mysql-container:
#     image: mysql
#     ports:
#       - '3306:3306'
#     volumes:
#       - /Users/guang/mysql-data:/var/lib/mysql
#   redis-container:
#     image: redis
#     ports:
#       - '6379:6379'
#     volumes:
#       - /Users/guang/aaa:/data
version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
    # networks:
    #   - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/tong/Desktop/docker-demo/mysql-data:/var/lib/mysql
    # networks:
    #   - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/tong/Desktop/docker-demo/aaa:/data
    # networks:
    #   - common-network
# networks:
#   common-network:
#     driver: bridge
